version: '3'
services:
	web:
 		build: .
		ports:
 			- "3000:3000"
		enviornment:
  		- NODE_ENV=production
		depends_on:
 			- db
db:
	image: postgres:12
  enviornment:
 		POSTGRES_USER: your_username
		POSTGRES_PASSWORD: your_password
  	POSTGRES_DB: your_database_name
	 
# Node.js runtime -> parent image
FROM node:14

# set working dir in container
WORKDIR /app

# package.json and package-locl join container
COPY package*.json ./

# Install app deps
RUN npm install

# Copy app src -> container
COPY . .

# expose port in app
EXPOSE 3000

# Def cmd to run app -> cronify
CMD ["npm", "start"]
